spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: always
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Qwer6786#
    username: root
    url: jdbc:mysql://localhost:3306/bobiShop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG


server:
  port: 8080

projectExam:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:123}
    remember.me.key: ${REMEMBER_ME_KEY:123}


